### ISSUE TITLE
options of  other models

### ISSUE THREAD

**Issue by jiangfeiyang** [mjq11302010044/Real-CE#8]
Thank you for providing the options for the RRDB model. However, where can I find the configuration options for other models? Could you provide the configuration options for text super-resolution models and the ELAN model?
Additionally, how can I determine which pair of data to use for training on the RealCE dataset under the x2 condition? Is any code modification required?

**Comment by mjq11302010044** [comment]
1. We currently provide only the model with the best performance (i.e., RRDB). For ELAN and other models, you can refer to the original repo or BasicSR repo for more details.
2. get_RealCE in basicsr/data/paired_image_dataset.py give an example for you to choose the training pair for X2, which is also written in our manuscript.
